version: 2
  shared: &shared
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      TERM: dumb
    steps:
      - checkout
      - run: sudo apt-get install -y make
      - run: mkdir -p ~/.nextflow/aws
      - run: rm $HOME/.gitconfig
      - run: mkdir -p "$HOME/.nextflow" && echo "providers.github.auth='$NXF_GITHUB_ACCESS_TOKEN'" > "$HOME/.nextflow/scm"
      - run: make test

jobs:
  java-9:
    docker:
      - image: circleci/openjdk:10-jdk
    <<: *shared

  java-9:
    docker:
      - image: circleci/openjdk:9-jdk
    <<: *shared

  java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *shared
