version: 2
shared: &shared
  environment:
    GRADLE_OPTS: -Dorg.gradle.daemon=false
    TERM: dumb
  working_directory: ~/nextflow
  steps:
    - checkout
    - run: sudo apt-get install -y make
    - run: mkdir -p ~/.nextflow/aws
    - run: rm $HOME/.gitconfig
    - run: mkdir -p "$HOME/.nextflow" && echo "providers.github.auth='$NXF_GITHUB_ACCESS_TOKEN'" > "$HOME/.nextflow/scm"
    - run: echo "org.gradle.daemon=false" > "gradle.properties"
    - run: make assemble
    - run: make check

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *shared

  build:
    docker:
      - image: circleci/openjdk:9-jdk
    <<: *shared

  build:
    docker:
      - image: circleci/openjdk:10-jdk
    <<: *shared



